baseURL = 'https://shubhxms.github.io/'
languageCode = 'en-us'
title = 'Shubham Shah'
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4

[params]
mode = "toggle"
useCDN = false
subtitle = ""
description = "personal website of shubham shah"
enableGitInfo = true
mathjax = true # enable MathJax support
katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/shubhxms/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/shubhxms/"

[[menu.main]]
name = "Now"
url = "/#now"
weight = 1

[[menu.main]]
name = "Core"
url = "/core"
weight = 3

[[menu.main]]
name = "Notes"
url = "/notes"
weight = 5

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "Shelf"
url = "/shelf"
weight = 6

[[menu.main]]
name = "Uses"
url = "/uses"
weight = 7

[permalinks]
  pages = '/:title'

[markup.goldmark.renderer]
unsafe= true

[outputFormats]
[outputFormats.data]
  mediaType = "text/html"
  isHTML = true

[outputs]
home = ["HTML", "data"]
